baseURL = "https://heyhler.github.io/SkeletronTest"
headerFontSize = 128
languageCode = "en-us"
publishDir = "docs"
theme = "skeletron"
title = "SkeletronTest"
[github]
	owner_name = "heyhler"
	repository_name = "SkeletronTest"
[menu]
	[[menu.footer]]
		identifier = "about"
		name = "About"
		url = "/about/"
	[[menu.footer]]
		identifier = "manual"
		name = "Manual"
		url = "/manual"
[params]
	project_name = "Skeletron"
